package hibernate;
// Generated 08-feb-2017 16:18:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal clienteId;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String email;
     private String telefono;
     private String dni;
     private Set coches = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(BigDecimal clienteId, String nombre, String apellido1, String email, String telefono, String dni) {
        this.clienteId = clienteId;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.email = email;
        this.telefono = telefono;
        this.dni = dni;
    }
    public Cliente(BigDecimal clienteId, String nombre, String apellido1, String apellido2, String email, String telefono, String dni, Set coches) {
       this.clienteId = clienteId;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.email = email;
       this.telefono = telefono;
       this.dni = dni;
       this.coches = coches;
    }
   
    public BigDecimal getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(BigDecimal clienteId) {
        this.clienteId = clienteId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Set getCoches() {
        return this.coches;
    }
    
    public void setCoches(Set coches) {
        this.coches = coches;
    }




}


