package hibernate;
// Generated 08-feb-2017 16:18:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Coche generated by hbm2java
 */
public class Coche  implements java.io.Serializable {


     private BigDecimal cocheId;
     private Cliente cliente;
     private String marca;
     private String matricula;
     private String modelo;
     private Date itv;

    public Coche() {
    }

    public Coche(BigDecimal cocheId, Cliente cliente, String marca, String modelo, String matricula, Date itv) {
       this.cocheId = cocheId;
       this.cliente = cliente;
       this.marca = marca;
       this.modelo = modelo;
       this.matricula = matricula;
       this.itv = itv;
    }
   
    public BigDecimal getCocheId() {
        return this.cocheId;
    }
    
    public void setCocheId(BigDecimal cocheId) {
        this.cocheId = cocheId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Date getItv() {
        return this.itv;
    }
    
    public void setItv(Date itv) {
        this.itv = itv;
    }




}


